parameters:
    huggingface_chat_model: 'meta-llama/Llama-3.1-8B-Instruct:cerebras'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    
    App\Service\LlmCommandInterpreterService:
        arguments:
            $huggingFaceToken: '%env(HUGGINGFACE_API_TOKEN)%'
            $huggingFaceModel: '%env(default:huggingface_chat_model:HUGGINGFACE_CHAT_MODEL)%'

    App\Service\InternalVoiceCommandInterpreterService:
        arguments:
            $huggingFaceToken: '%env(HUGGINGFACE_API_TOKEN)%'
            $huggingFaceModel: '%env(default:huggingface_chat_model:HUGGINGFACE_CHAT_MODEL)%'

   